<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>ir.onto</groupId>
  <artifactId>ontlas</artifactId>
  <version>0.0.1</version>
  <name>Ontology-driven Atlas</name>
  <url>http://ontlas.onto.ir</url>
  <inceptionYear>2016</inceptionYear>
  <licenses>
		<license>
			<name>MIT License</name>
			<url>http://www.opensource.org/licenses/mit-license.php</url>
			<distribution>repo</distribution>
		</license>
	</licenses>
  <organization>
    <name>Onto</name>
    <url>http://onto.ir</url>
  </organization>
  <developers>
    <developer>
      <id>morteza</id>
      <name>Morteza Ansarinia</name>
      <email>ansarinia@me.com</email>
      <url>http://github.com/morteza</url>
      <organization>ICSS</organization>
      <organizationUrl>http://www.iricss.org</organizationUrl>
      <roles>
        <role>architect</role>
        <role>developer</role>
      </roles>
    </developer>
  </developers>
  <contributors></contributors>

  <properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

  <dependencies>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-core</artifactId>
      <version>3.3.2</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-unit</artifactId>
      <version>3.3.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-mongo-client</artifactId>
      <version>3.3.2</version>
    </dependency>
    <dependency>
    	<groupId>io.vertx</groupId>
    	<artifactId>vertx-web</artifactId>
    	<version>3.3.2</version>
    </dependency>
    <dependency>
      <groupId>net.sourceforge.owlapi</groupId>
      <artifactId>owlapi-api</artifactId>
      <version>5.0.2</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.5.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>2.4.3</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <transformers>
                <transformer
                  implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <manifestEntries>
                    <Main-Class>io.vertx.core.Starter</Main-Class>
                    <Main-Verticle>ir.onto.ontlas.AtlasVerticle</Main-Verticle>
                  </manifestEntries>
                </transformer>
              </transformers>
              <artifactSet/>
              <outputFile>${project.build.directory}/${project.artifactId}-${project.version}-fat.jar</outputFile>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>io.dazraf</groupId>
        <artifactId>vertx-hot-maven-plugin</artifactId>
        <version>2.1.0</version>
        <configuration>
            <verticleReference>ir.onto.ontlas.AtlasVerticle</verticleReference>
            <!--<configFile>config filename</configFile>-->
        </configuration>
    </plugin>
    </plugins>
  </build>

</project>
